
APPTARGET = ""

ENTRY_PT = 

OBJS = 

SOURCES = 

LOCAL_COPTS = 

EXEDIR=../exe

SHARED_LIB_LINK = 

BUILD_TYPE = CFE_APP

include ../cfe/cfe-config.mak

include ../cfe/debug-opts.mak

include //make/compiler-opts.mak

INCLUDE_PATH = -I/inc -I/inc -I/inc -I//inc -I/inc -I//fsw/src -I -I../cfe/inc -I../inc

VPATH = //fsw/src 

include /make/app-rules.mak
